name: messaging_bloc
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  http: ^0.13.4
  equatable: ^2.0.3
  firebase_core: ^1.17.0
  firebase_auth: ^3.3.18
  auto_route: ^4.0.1
  provider: ^6.0.2
  cloud_firestore: ^3.1.15
  crypto: ^3.0.2
  flutter_native_splash: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^4.0.0
  build_runner: ^2.1.11

flutter:
  assets:
    - assets/images/320_placeholder.png

flutter_native_splash:
  color: "#221242"
  image: assets/splash.png

  
  