// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW0xGupftSIWLaAl67vHRUMxJMu0r2UzU',
    appId: '1:882184378173:web:542564126e459708345754',
    messagingSenderId: '882184378173',
    projectId: 'messaging-bloc',
    authDomain: 'messaging-bloc.firebaseapp.com',
    storageBucket: 'messaging-bloc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrVnoq5j-9RAYR8H-X05aIPqb17_LL_nM',
    appId: '1:882184378173:android:7f1ff602cd929caa345754',
    messagingSenderId: '882184378173',
    projectId: 'messaging-bloc',
    storageBucket: 'messaging-bloc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAWKxch21NtpelQ0k9vMo29xou_xsTZFw',
    appId: '1:882184378173:ios:0b74bbdcd8017263345754',
    messagingSenderId: '882184378173',
    projectId: 'messaging-bloc',
    storageBucket: 'messaging-bloc.appspot.com',
    iosClientId: '882184378173-odjs1o96h5b2mglt7l48ak769lqg0p9f.apps.googleusercontent.com',
    iosBundleId: 'com.example.messagingBloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAWKxch21NtpelQ0k9vMo29xou_xsTZFw',
    appId: '1:882184378173:ios:0b74bbdcd8017263345754',
    messagingSenderId: '882184378173',
    projectId: 'messaging-bloc',
    storageBucket: 'messaging-bloc.appspot.com',
    iosClientId: '882184378173-odjs1o96h5b2mglt7l48ak769lqg0p9f.apps.googleusercontent.com',
    iosBundleId: 'com.example.messagingBloc',
  );
}
